In [1]:
# Implementation of Option strategies
# ------------------------------------------------------------------------------
# Program that constructs Option trading strategies using plain vanilla options
# Object Oriented Programming principles have been applied like Inheritance and 
# Polymorphism.
# ------------------------------------------------------------------------------
# As an example "Long Butterfly" option strategy is implemented and the trade 
# is the following:
# Buy one call at A, 
# Sell two calls at higher strike B
# Buy one call at an even higher strike C.
# ------------------------------------------------------------------------------
# Market expectation: Direction neutral/volatility bearish. In this case, 
# the holder expects the underlying to remain around strike B, or it is felt 
# that there will be a fall in implied volatility. Position is less risky than 
# selling straddles or strangles as there is a limited downside exposure.
# ------------------------------------------------------------------------------
# Profit & loss characteristics at expiry:
#
# Profit: Maximum profit limited to the difference in strikes between A and B 
# minus the net cost of establishing the position. Maximised at mid strike B 
# (assuming A-B and B-C are equal).
#
# Loss: Maximum loss limited to the net cost of the position for either a rise 
# or a fall in the underlying.
#
# Break-even: Reached when the underlying is higher than A or lower than C by 
# the cost of establishing the position.
#
# DEUTSCHE LUFTHANSA ORD with ISIN: DE0008232125 serves as the Underlying in 
# this example.
# ------------------------------------------------------------------------------

import numpy as np
import pandas as pd
from Derivatives.Portfolio import Portfolio
from Derivatives.Options.Option import Option
from Derivatives.Options.PlainVanillaOption import PlainVanillaOption
from Derivatives.Options.BarrierOption import BarrierOption

In [2]:
# Step 1 - Set up the options with the following parameters
# ------------------------------------------------------------------------------
# Spot price = 11.10, 
# Time to maturity 1 year = 1
# Risk-free interest rate = 0.05
# Implied volatility = 0.30
# Multiplier = 100 for LHA options. Contract size 100 for long option, 200 for 
# the short option
# Strike prices = Call A: 11, Call B = 9, Call C = 13
#------------------------------------------------------------------------------

#option_1 = PlainVanillaOption(11.10, 11, 1, 0.05, 0.30,'call','Short', 2, 1)    
#option_2 = PlainVanillaOption(11.10, 9, 1, 0.05, 0.30, 'call', 'Long', 1, 1)      
#option_3 = PlainVanillaOption(11.10, 13, 1, 0.05, 0.30, 'call','Long', 1, 1) 

#option_1.calculate_option_price_BS_formula() 
#option_2.calculate_option_price_BS_formula() 
#option_3.calculate_option_price_BS_formula() 

#portfolio = Portfolio('Long Butterfly')
#portfolio.add_product(option_1)
#portfolio.add_product(option_2)
#portfolio.add_product(option_3)

#portfolio.calculate_premium_strategy()

#portfolio.calculate_payoff_strategy()

#long_call = PlainVanillaOption(8, 7, 1, 0.05, 0.30, 'call','Long', 1, 1) 
#long_call_down_in = BarrierOption(8, 7, 1, 0.05, 0.30, 'call','Long', 1, 1, 'down-and-in', 11, 0) 
#long_call_down_out = BarrierOption(8, 7, 1, 0.05, 0.30, 'call','Long', 1, 1, 'down-and-out', 11, 0) 

#long_call.calculate_option_price_BS_formula() 
#long_call_down_in.calculate_option_price_BS_formula() 
#long_call_down_out.calculate_option_price_BS_formula() 

#portfolio = Portfolio('Barrier Option')
#portfolio.add_product(long_call)
#portfolio.add_product(long_call_down_in)
#portfolio.add_product(long_call_down_out)

#portfolio.calculate_premium_strategy()

#portfolio.calculate_payoff_strategy()

#long_call.price, long_call_down_in.price, long_call_down_out.price, + long_call_down_out.price+long_call_down_in.price
#long_call.get_option_payoff()
#long_call.get_option_VAR()

In [3]:
#Step 2 - Price individually the options and calculate their risk measures. 
# The options will then be added in the portfolio
# ------------------------------------------------------------------------------
# Option 1: Short call @11, 200 contracts of 100 options each

# Pricing using the closed-end formula of B&S. Uncomment for usage. 
#option_1.calculate_option_price_BS_formula() 

# In this example the MC method has been used for the pricing of the Option 1
#option_1.calculate_option_price_MC_BS() 

# Calculate Option 1 greeks: Delta, Gamma, Vega
#option_1.calculate_option_greeks()    
 
# Get all the information for Option 1. Uncomment to use
#option_1.get_option_properties()

In [4]:
# ------------------------------------------------------------------------------
# Option 2: Long call @9, 100 contracts of 100 options each

# In this example the MC method has been used for the pricing of the Option 2
#option_2.calculate_option_price_MC_BS()         

# Calculate Option 2 greeks: Delta, Gamma, Vega
#option_2.calculate_option_greeks()       

# Get all the information for Option 1. Uncomment to use
#option_2.get_option_properties()

In [5]:
# ------------------------------------------------------------------------------
# Option 3: Long call @13, 100 contracts of 100 options each

# In this example the MC method has been used for the pricing of the Option 3
#option_3.calculate_option_price_MC_BS() 

# Calculate Option 3 greeks: Delta, Gamma, Vega
#option_3.calculate_option_greeks()  

# Get all the information for Option 1. Uncomment to use
#option_3.get_option_properties()

In [6]:
#Step 3 - Create the empty portfolio and add the options in it

#portfolio = Portfolio('Long Butterfly')
#portfolio.add_product(option_1)
#portfolio.add_product(option_2)
#portfolio.add_product(option_3)

In [7]:
# portfolio.calculate_premium_strategy()

In [8]:
#portfolio.calculate_payoff_strategy()

In [9]:
# ------------------------------------------------------------------------------
# As a conclusion we total premium paid for entering in this strategy is around 
# 4,950 Euros and this amount is the total risk of the strategy.
# The maximum gain from the strategy could be approximately 15,050 Euros.

In [19]:
stock_data = pd.read_csv("/Users/thanef/Desktop/Project_Python_Trading_strategies/code/data/stocks_data.csv")

In [17]:
import os
dirname = os.path.dirname(__file__)

NameError: name '__file__' is not defined

In [18]:
os.path.abspath('')

'/Users/thanef/Desktop/Project_Python_Trading_strategies/code'

In [20]:
stock_data

,Date,ATHENS GENERAL INDEX,LAMDA,JUMBO,MYTILINAIOS,AEGEAN,OTE,OPAP,TERNA,DEH,TPEIRAIWS,ETE,EUROBANK,ALPHA
0,19/02/2021,781.42,6.5100,13.3500,12.8000,4.4400,12.3100,10.4500,12.3000,9.3300,0.7660,2.0190,0.5594,0.7692
1,18/02/2021,782.23,6.5600,13.1000,12.7000,4.3900,12.3900,10.4700,13.7800,9.0500,0.7562,1.9995,0.5500,0.7690
2,17/02/2021,788.75,6.5100,13.3500,12.9700,4.3550,12.5900,10.5900,13.8000,8.7250,0.8020,2.0780,0.5640,0.7852
3,16/02/2021,795.91,6.5300,13.6100,13.1800,4.3500,12.8500,10.7300,14.1200,8.4500,0.8400,2.0980,0.5700,0.8090
4,15/02/2021,796.38,6.6700,13.5000,12.8200,4.2700,12.6000,10.7600,14.5000,8.3500,0.8150,2.1260,0.5776,0.8300
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1677,17/04/2014,1248.61,5.2169,9.6185,5.8788,4.5504,9.5759,5.9286,3.1996,4.8631,3420.0000,471.0000,39.0807,34.7500
1678,16/04/2014,1218.00,5.1313,9.0700,5.7830,4.3972,9.2004,5.4638,3.0579,4.6161,3500.0000,445.5000,37.7913,34.5000
1679,15/04/2014,1186.99,4.9090,8.7838,5.4695,4.4095,8.6200,5.3018,2.9833,4.3861,3580.0000,456.0000,40.2710,33.8500
1680,14/04/2014,1207.82,4.8919,9.2131,5.6785,4.4279,8.8163,5.2862,3.0206,4.4713,3460.0000,489.0000,39.8743,34.2000
1681,11/04/2014,1250.80,5.2682,9.4595,5.9224,4.5320,9.3028,5.4846,3.1101,4.7140,3580.0000,556.5000,42.9492,35.0500